site_name: k8s demonstration
markdown_extensions:
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
theme:
  name: material
nav:
  - Home: index.md
  - Kubernetes?:
    - what_is_k8s/index.md
    - what_is_k8s/working_with_k8s.md
  - Demo app:
    - demo_app/index.md
    - demo_app/infrastructure.md
    - demo_app/platform.md
    - demo_app/the_app.md
  - lessons.md