site_name: k8s demonstration
markdown_extensions:
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
theme:
  name: material
