apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      serviceAccountName: demo-api-sa
      containers:
        - name: api
          image: ghcr.io/northo/k8s-webserver-with-inference-job-demo-api:sha-f460441
          env:
            - name: ARGO_HOST
              value: "https://argo-server.argo.svc:2746"
            - name: AZURE_STORAGE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: my-azure-storage-credentials
                  key: account-access-key
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"

