apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
  namespace: demo
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      labels:
        app: demo-api
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: demo-api-sa
      containers:
        - name: api
          image: ghcr.io/northo/k8s-webserver-with-inference-job-demo-api:sha-9e11e8e
          env:
            - name: ARGO_HOST
              value: "https://argo-server.argo.svc:2746"
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"

