apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-api-sa
  namespace: demo
  annotations:
    azure.workload.identity/client-id: "/subscriptions/08c38d25-f29d-4354-9240-07269d516415/resourceGroups/k8s-demo-application/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aks-storage-identity"
