apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-submittable
  namespace: argo
spec:
  arguments:
    parameters:
      - name: message
        value: hello world
  templates:
    - name: modify-message
      inputs:
        parameters:
          - name: message
      outputs:
        artifacts:
          - name: modified-message
            globalName: modified-message
            path: /tmp/message-out.txt
            archive:
              none: {}
      container:
        image: busybox
        command: [sh, -c]
        args: ["echo {{inputs.parameters.message}} has been modified | tee /tmp/message-out.txt"]
