apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-submittable
  namespace: argo
spec:
  arguments:
    parameters:
      - name: message
        value: hello world
  templates:
    - name: print-message
      inputs:
        parameters:
          - name: message
      outputs:
        artifacts:
          - name: the-script
            path: /tmp/message.txt
            s3:
              key: "{{workflow.uid}}"
      container:
        image: busybox
        command: [sh, -c]
        args: ["echo {{inputs.parameters.message}} | tee /tmp/message.txt"]
