apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-submitter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-submitter
  template:
    metadata:
      labels:
        app: job-submitter
    spec:
      containers:
        - name: app
          image: ghcr.io/northo/job-submitter:latest
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"

