apiVersion: v1
kind: Service
metadata:
  name: job-submitter
  namespace: default
spec:
  selector:
    app: job-submitter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP

