apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-submitter
  namespace: default
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-submitter-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default  # or the name of your service account
    namespace: default
roleRef:
  kind: Role
  name: job-submitter
  apiGroup: rbac.authorization.k8s.io

