services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - ARGO_HOST=https://host.docker.internal:2746
    env_file:
      - .env
    command: ["--host", "0.0.0.0", "--port", "8000", "--reload"]
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml 
