apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/argoproj/argo-workflows/releases/download/v3.6.10/quick-start-minimal.yaml
- ingress.yaml
- sa-default.yaml
patches:
- path: cm-artifact-repo-patch.yaml
  target:
    kind: ConfigMap
    name: artifact-repositories
    version: v1
