apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/argoproj/argo-workflows/releases/download/v3.6.10/quick-start-minimal.yaml
  - ingress.yaml
patches:
  - target:
      group: ""
      version: v1
      kind: ConfigMap
      name: artifact-repositories
    path: cm-artifact-repo-patch.yaml
